#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

preview() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
}

TEMPDIR=$HOME/.cache

file="$1"; shift
case "$(basename "$file" | tr '[A-Z]' '[a-z]')" in
*.tar*) tar tf "$file" ;;
*.zip) unzip -l "$file" ;;
*.rar) unrar l "$file" ;;
*.7z) 7z l "$file" ;;
*.avi|*.mp4|*.mkv|*.webm)
	thumbnail="$TEMPDIR/thumbnail.png"
  ffmpegthumbnailer -i "$file" -o "$thumbnail" -s 0
	preview "$thumbnail"
	;;
*.mp3|*.flac|*.wav)
  mediainfo "$file"
  ;;
*.pdf)
	thumbnail="$TEMPDIR/thumbnail.png"
	gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
  preview "$thumbnail"
	;;
*.jpg|*.jpeg|*.png|*.bmp|*.face|*.webp)
  preview "$file"
    ;;
*.ttf|*.otf|*.woff)
	thumbnail="$TEMPDIR/thumbnail.png"
	fontpreview -i "$file" -o "$thumbnail"
	preview "$thumbnail"
	;;
*.svg)
	thumbnail="$TEMPDIR/thumbnail.png"
	convert "$file" "$thumbnail"
	preview "$thumbnail"
	;;
*.gz)
  man "$file"
  ;;
*) bat --color always "$file" ;;
esac
return 127

